### ISSUE TITLE
Should be available through composer.

### ISSUE THREAD

**Issue by elliotchance** [XeroAPI/XeroOAuth-PHP#19]
This library should be available as a composer package.

**Comment by dmseaton** [comment]
Aside from recently embracing Composer (and heartily +1ing it), I'll add that the presence of the composer file in many, many libraries which I've used in the past never caused me the slightest inconvenience.

**Comment by elliotchance** [comment]
Since xero is totally unwilling to fix up their code, or allow anyone else to, the new community package will be at: https://github.com/elliotchance/xero-api

**Comment by naderman** [comment]
Wow this is kind of ridiculous, over half a year ago, and you still haven't addressed this. Do any of the people maintaining this library even work on PHP projects these days?

**Comment by elliotchance** [comment]
It's clear Xero are not PHP developers, otherwise this discussion would of never begun. The true loss here is not that composer support is missing, it's that they are far to arrogant and naive to let anybody help them.

**Comment by allmyitjason** [comment]
:+1:

**Comment by ilijastuden** [comment]
+1. Composer is de facto standard package manager for PHP and what you have here is a package that other projects depend on. By adding composer support to your package, you'll make it available to more developers and easily discoverable (first place where I search for libraries is always Packagist.org).

**Comment by overcrookd** [comment]
This has in fact become obligatory, pretty much same as using version control, why clutter the source code with .git* files if "some" people don't use git
> the benefits of the many outweigh the benefits of the few

**Comment by tiran133** [comment]
bump +1

**Comment by iampersistent** [comment]
> Sorry but I am not keen to add anything to the project that is not of utility to all - since not everyone will want / need composer support, I don't want to add it in, even if that is an inconvenience to those that are fans.
> @ronanq 

I'm a fan of Pearl Jam and as a fan, it would be unreasonable to ask you to include a file with Pearl Jam's discography. But this isn't about being a fan, its about using the right tools to do the job.

I do not know of a single php framework that doesn't use composer. I don't know of any major php libraries that don't use composer. When I deploy sites, I depend on composer to make sure the correct versions of the libraries are being deployed.

Please, be reasonable here and add composer support. Honestly its pretty sad that as developers we are begging for support for a standard tool.

**Comment by overcrookd** [comment]
@iampersistent Besides, the implementation couldn't be any easier...

**Comment by paulsschwarz** [comment]
Take a look at this https://github.com/calcinai/xero-php I've had great success using it.

**Comment by ronanq** [comment]
Thanks everyone for your opinions and feedback. Some very valid and reasonable arguments why we should rethink this.

As soon as we have some time we will:
- Look at adding composer support
- Look at our options on overhauling PHP support totally

Unfortunately we won't have time to do so for a little while yet, but please hang tight.
And before anyone says 'it is just a quick change' - yes it is, and as soon as we have cleared some time to setup composer, test the change and deploy it, we will do so!

**Comment by nfauchelle** [comment]
@paulsschwarz 
That looks interesting, might take that up on the next project thanks.

**Comment by elliotchance** [comment]
@ronanq Forgive me, but I don't believe you. People have been screaming for this for a year and the only response we get is "still not doing it, maybe in the future" - how is this any different from the situation we were already in?

Do not confuse composer support with fixing code. Composer support is one file added to the codebase and registering the package on packagist.org - it's a matter of minutes and will not break existing implementations.

I truly hope you prove me wrong.

**Comment by coop182** [comment]
+1 for composer support.

**Comment by wilr** [comment]
+1 Composer support is trivial to add and maintain and would bring this in line with most modern libraries.

**Comment by paulstatezny** [comment]
+1 Getting on composer/Packagist is the de facto method for publishing PHP libraries for other developers to use. This would increase your adoption many times over.

**Comment by edmarriner** [comment]
I would really back this too! Composer is a must it you want to adoption to continue!

**Comment by cbakker** [comment]
Because I was sick the wait, I created my own Xero API client. Namespaced and with Composer support.

Check it out: https://github.com/picqer/xero-php-client

It only supports private apps, because that is all I need. But if others want to contribute, please be my guest to send me any Pull Requests.

**Comment by coop182** [comment]
We have started using https://github.com/calcinai/xero-php here at Common Ledger in production... We have made a few small changes to get it working for partner apps but we are now full steam ahead...

**Comment by cbakker** [comment]
That looks very well done @coop182. I am sure they put a lot more time in it then I did. :)

Funny how many projects started for Xero PHP clients, because Xero refused to add one little JSON file "that is not of utility to all".

**Comment by tiran133** [comment]
I call it ignorance and underestimating the power of the community. Honestly I don't even want to use this package any more. The other ones look so much better...

**Comment by coop182** [comment]
Yeah @calcinai has done an awesome job. I really like that your client uses guzzle though @cbakker, its something that has been requested to be added to @calcinai's library and when we get a bit more time we will do it... I think it will be really robust once that is in place :smile:

**Comment by calcinai** [comment]
It pains me that that issue is still lingering! I had a quick crack at dropping Guzzle in but got a little caught up with provisions for Public/Partner apps. I will have another go when I get some free time.

**Comment by gerrywastaken** [comment]
^ lol, typical Xero. No close message, although it looks like the file has been added.

**Comment by cbakker** [comment]
Yep, very lazy developers with no empathy for clients/users

**Comment by gerrywastaken** [comment]
@cbakker I doubt it's a problem caused by bad devs. It's seen at all levels of Xero support related to the API, so I suspect priorities have drastically changed inside of Xero and they now see the API as a burden instead of an asset.

**Comment by gerrywastaken** [comment]
Another developer got so fed up with this library that he started a replacement from scratch: https://github.com/calcinai/xero-php

The code is MUCH better and he is very responsive to bug reports and pull requests. I suggest everybody start putting their effort in over there instead.

**Comment by nickion** [comment]
@gerrywastaken "It's seen at all levels of Xero support related to the API". So it seems. I've recently coined the phrase "If Xero used Xero it would be different", as it seems more than probable that they don't. Finding that the trivial task of making the API available via composer still isn't done, I guess I should give up my long held desire for a reconciliation API.
