### ISSUE TITLE
Bug found

### ISSUE THREAD

**Issue by ryanmitchell** [XeroAPI/XeroOAuth-PHP#21]
Hello

There's a bug in the codebase when you do 2 simultaneous requests - it isn't apparent in the test suite as this never happens.

e.g. make a GET request, then a POST request and you will be supplied with an oauth invalid signature error.

As a work around at the end of the "curlit" method I reset a few variables:

```
    $this->request_params = array();
    $this->params = array ();
    $this->headers = array ();
    $this->auto_fixed_time = false;
    $this->buffer = null;
    $this->xml = null;
```

After that everything works as expected.

Hope this helps someone else, as it had me knocking my head off a wall for a long time!

Ryan

**Comment by prakash9986** [comment]
Hi Ronanq, 

How to fix the simmilar issue, when using Devid Pitman's php wrapper. The solution given on https://github.com/XeroAPI/XeroOAuth-PHP/issues/21 this is based on XeroOAuth php wraper.

I have come accross with simillar issue when generating multiple invoices and setting SummarizeErrors=false

I got this error: oauth_problem=signature_invalid&oauth_problem_advice=Failed%20to%20validate%20signature 

Thanks
