### ISSUE TITLE
Curl error: SSL certificate problem

### ISSUE THREAD

**Issue by asnanblt** [XeroAPI/XeroOAuth-PHP#31]
Hi 

I got a problem when testing.

http://salnan.com/xero/public.php

For 1st time it work ok when i test Organization. But after i close my windows, and then open again, it say

Error: Curl error: SSL certificate problem, verify that the CA cert is OK. Details: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

Any solution for this. I dont update any code from your server, Only consumer_key , shared_secret, and also OAUTH_CALLBACK

Thank You
Salnan

**Comment by ronanq** [comment]
I don't know of any reason for this, post in our developer forums if you still need help: https://community.xero.com/developer/
