### ISSUE TITLE
$config overwritten

### ISSUE THREAD

**Issue by foaly-nr1** [XeroAPI/XeroOAuth-PHP#34]
It doesn't really make sense to me to overwrite the passed config with defaults. Shouldn't it be the other way round as they are called 'defaults'? Would be useful to change the curl timeout for instance. I'm submitting a month's invoices in one call so it's timing out too early.

https://github.com/XeroAPI/XeroOAuth-PHP/blob/master/lib/XeroOAuth.php#L90

**Comment by foaly-nr1** [comment]
Issued a pull request. Sorry for the double post.

https://github.com/XeroAPI/XeroOAuth-PHP/pull/35

**Comment by ronanq** [comment]
Completed in #35
