### ISSUE TITLE
when attempting to access with Partner type

### ISSUE THREAD

**Issue by yys0623** [XeroAPI/XeroOAuth-PHP#36]
it returns below errors:

ContextErrorException: Notice: Undefined index: signed_url 

looking at a line 264: you will see CURLOPT_URL => $this->sign['signed_url'],

where is the sign['signed_url'] from?????

think it's not implemented yet huh?

**Comment by ronanq** [comment]
The best place to get support on implementing is the Xero forums https://community.xero.com/developer/topic/16971/
