### ISSUE TITLE
SHA-2?

### ISSUE THREAD

**Issue by elliotchance** [XeroAPI/XeroOAuth-PHP#48]
Can you please confirm that your official API works with your API so people don't have to test SHA-2 specifically.

**Comment by elliotchance** [comment]
Nevermind, the SHA-2 is only for the server certificate not eh SDK itself.

**Comment by ronanq** [comment]
Yes indeed - there should be no need to change anything within the SDK itself.

If you or anyone else reading this has any specific issues they encounter when testing, you can get assistance here: https://community.xero.com/developer/discussion/11526709/.
