### ISSUE TITLE
Add option to disable ipv6

### ISSUE THREAD

**Issue by raintonr** [XeroAPI/XeroOAuth-PHP#52]
There is a known issue with some platforms (specifically AWS) that makes this library slow. Discussed here:

https://forums.aws.amazon.com/thread.jspa?messageID=638216

This can be overcome by adding `CURLOPT_IPRESOLVE => CURL_IPRESOLVE_V4` in the connection options, but clearly that isn't desirable for everyone.

Some way to optionally disable this in the constructor config might be nice.

**Comment by ronanq** [comment]
Hi there

It is possible to add curl option overrides already, try adding something like this:
$signatures = array (
		'consumer_key' => 'YOURCONSUMERKEY',
		'shared_secret' => 'YOURSECRET',
		'CURLOPT_IPRESOLVE' => CURL_IPRESOLVE_V4,
		// API versions
		'core_version' => '2.0',
		'payroll_version' => '1.0',
		'file_version' => '1.0' 
);

It would be quite useful to get some more details on this as we had some random reports of AWS network issues previously, but the link you provided is the first really concrete piece of info we got to go on.

If you could drop us a line here (http://developer.xero.com/contact-xero-developer-platform-support/) with some details so we can see your app logs, confirm what AWS region you are in and also advise you when we have resolved the issue, that would help a lot :)

**Comment by raintonr** [comment]
There really is nothing to see in the app logs.

You can see that the AAAA DNS doesn't work from this example on the AWS host:

```
$ time dig api.xero.com A

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.5 <<>> api.xero.com A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53237
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;api.xero.com.			IN	A

;; ANSWER SECTION:
api.xero.com.		2411	IN	CNAME	wip.api.xero.com.
wip.api.xero.com.	30	IN	A	198.61.252.39

;; Query time: 208 msec
;; SERVER: 172.31.0.2#53(172.31.0.2)
;; WHEN: Tue Nov 24 12:04:51 UTC 2015
;; MSG SIZE  rcvd: 75


real	0m0.215s
user	0m0.004s
sys	0m0.003s
$ time dig api.xero.com AAAA

; <<>> DiG 9.9.4-RedHat-9.9.4-18.el7_1.5 <<>> api.xero.com AAAA
;; global options: +cmd
;; connection timed out; no servers could be reached

real	0m15.007s
user	0m0.002s
sys	0m0.005s
```

This is running in the AWS zone ap-southeast-2a.

When I run the above AAAA lookup on my local host the result comes back instantly.

**Comment by ronanq** [comment]
Sorry @raintonr - a very late reply to this, but our network engineer and AWS engineers apparently found an issue somewhere that was causing this.

Hopefully it has been sorted for you - I understand it should no longer be an issue.

**Comment by raintonr** [comment]
No problem. Glad you got to the bottom of it.

**Comment by elliotchance** [comment]
@ronanq are you going to close this issue?

**Comment by raintonr** [comment]
Looks fixed to me.
