### ISSUE TITLE
Need help to fix Unknown SSL protocol error in connection during refresh tokens

### ISSUE THREAD

**Issue by chethank** [XeroAPI/XeroOAuth-PHP#57]
Hi,
I am using PHP library to access Xero API's and when trying to refresh API tokens I am getting the following error,
"Curl error: Unknown SSL protocol error in connection to api-partner.network.xero.com:443".
It's not happening for all request, but for few.
Can you please let me know how it can be fixed. Below is the complete response,

REQUEST API URL:
https://api-partner.network.xero.com/oauth/AccessToken

RESPONSE CODE:1

RESPONSE:
https://gist.github.com/chethank/af642cdd5379a5eb9119

Thanks
Chethan K

**Comment by philals** [comment]
Hi Chethan

How long has this been happening?

Did you test your integration before the SHA2 migration? 

http://developer.xero.com/sha2-ssl-cert-migration-advisory-notice/

**Comment by chethank** [comment]
Hi Phil,
I see the errors occur or few request (not all during refresh tokens) from around mid December 2015 till Feb 2016. And the SHA2 migration happened in March 2016, so I am not sure if it's related to that. Also I had test my integration with SHA2 and had no issues.

**Comment by Scandy185** [comment]
You are not sure, but yet you are posting in Twitter to sell SSL Protocol Token? Better credit me or refund me! Here is my transaction hash: 

0xc27987d242a098aaee42f0e5daa260e842df6ae5a36b61829f10bd6cdf6d505c

**Comment by SidneyAllen** [comment]
Hi @Scandy185 

I want to make sure you are aware that this repository is no longer maintained.  Please see the README. 

With the release of OAuth 2.0 support Xero is rolling out new official SDKs supported by Xero.  PHP is one of the languages we will be supporting.  

If you are just starting, I highly recommend going with OAuth 2.0 and our new SDKs.
https://github.com/XeroAPI/xero-php-oauth2

Sample app
https://github.com/XeroAPI/xero-php-oauth2-app
