### ISSUE TITLE
Not creating $this->request_params for POST requests in curlit() was breaking OAuth signature

### ISSUE THREAD

**Issue by schmoove** [XeroAPI/XeroOAuth-PHP#9]
I was receiving the following warnings doing a POST to /Invoices, which was returning a 401 Invalid Signature from the API:

```

A PHP Error was encountered

Severity: Warning

Message: Illegal string offset 'xml'

Filename: libraries/XeroOAuth.php

Line Number: 303
A PHP Error was encountered

Severity: Warning

Message: Invalid argument supplied for foreach()

Filename: libraries/XeroOAuth.php

Line Number: 329
A PHP Error was encountered

Severity: Warning

Message: implode(): Invalid arguments passed

Filename: libraries/XeroOAuth.php

Line Number: 332
```

these pointed to the empty POST method switch on Line 226:

```
case 'POST':

    break;
```

Simply creating the empty array, ala: 

```
case 'POST':
    $this->request_params = array();
    break;
```

(or better yet before the switch on 225) fixed the issue, but I am wondering why this whole block was left empty???

**Comment by brettflorio** [comment]
@schmoove Thanks for reporting this, and @ronanq thanks for fixing this one. Just ran into it while modifying our integration to make multiple requests. Updating to the latest code fixes it.
